### ISSUE TITLE
How to get lines of code for badge

### ISSUE THREAD

**Issue by 8ctopus** [iRyanBell/scc-docker-action#10]
Just spent some time to figure it out and thought I would share it so others don't need to spend time on this

```yml
      - name: Get lines of code
        id: scc
        uses: iryanbell/scc-docker-action@v1.0.2
        with:
          args: ${{ env.workspace }} -i php --exclude-dir vendor --format json src

      - name: Echo scc output
        run: |
          echo -n "${{ steps.scc.outputs.scc }}"
          echo -n "${{ fromJson(steps.scc.outputs.scc)[0].Lines }}"
```
