### ISSUE TITLE
No output

### ISSUE THREAD

**Issue by ede-wolf-gls** [iRyanBell/scc-docker-action#2]
The README mentions, that the `scc` output is pushed to the step output. But this doesn't work. Example:
```yaml
#...
steps:
  - id: scc
    uses: iryanbell/scc-docker-action@v1.0.0
    with:
      args: ${{ env.workspace }}

  - name: Report lines of code
    run: echo "${{steps.scc.outputs.scc}}" > "scc.txt"
```
I only get an empty file with these steps.
